### ISSUE TITLE
Clone the repository to retain it safely in the future

### ISSUE THREAD

**Issue by pattacini** [gmmarconi/test-collatz-conjecture-with-yarp-gmmarconi#2]
Hi @gmmarconi 

To retain this repository in the future no matter what, you should clone it (don't fork) and store it safely on GitHub account.

I've recently realized that deleting the assignment from the GitHub Education dashboard will cause that all the participant repositories will be deleted too 😲, even if their ownership has been transferred.

**Comment by gmmarconi** [comment]
Cloned the repo [here](https://github.com/gmmarconi/test-collatz-conjecture-with-yarp-gmm). Thanks @pattacini.
